# Site settings
title: Free Range Factory
author: Fabrizio
email: contact@freerangefactory.org
description: "The best place for your embedded designs."
rel-author: "https://freerangefactory.org"
rel-publisher: "https://freerangefactory.org"

baseurl: "/" # change it if your site goes inside a subfolder.
             # For example: baseurl: "/site/"

url: "http://freerangefactory.org"
#url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown
#redcarpet:
#    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: :compressed
