# Site settings
title: Free Range Factory
email: contact@freerangefactory.org
description: "The best place to improve your embedded design skills."
rel-author: "https://freerangefactory.org"
rel-publisher: "https://freerangefactory.org"

baseurl: ""
#url: "http://freerangefactory.org"                          # FINAL PRODUCT
#url: "http://fabriziotappero.github.io/freerangefactory.org"# DEVELOPMENT ONLINE
url: "http://localhost:4000/"                                # DEVELOPMENT LOCAL

# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: :compressed
